# Base image untuk Node.js
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN yarn install

# Copy semua file proyek
COPY . .

# Set environment variable untuk Next.js
ENV NODE_ENV=development

# Copy file .env.production
COPY .env.development .env

# Jalankan aplikasi
CMD ["yarn", "dev"]
